# Generated by Django 2.1.7 on 2019-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='sinal',
            field=models.IntegerField(default=1),
        ),
    ]
