# Generated by Django 2.1.7 on 2019-03-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0003_auto_20190309_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretora',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
    ]
