# Generated by Django 2.1.7 on 2019-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0004_auto_20190309_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='rendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
